name: Demo
on:
  workflow_dispatch:
  push:
    branches:
      - demo2
jobs:
  deploy:
    name: Deploy
    runs-on: macos-11.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: SSH Agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.STRIKE_SSH_PRIVATE_KEY_GITHUB_ACTIONS }}
      - name: Add GitHub to known_hosts
        run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - name: Force Xcode 14.1
        run: sudo xcode-select -switch /Applications/Xcode_14.1.app
      - name: Install gpg
        run: brew install gnupg
      - name: Install ImageMagick
        run: brew install imagemagick
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/scripts/decrypt_secrets.sh
      - name: Modify App Icon
        env:
          ICON_RIBBON: Demo
        run: ./.github/scripts/modify_icon.sh
      - name: Archive project
        env:
          SCHEME: "Censo (Demo2)"
          CONFIGURATION: "Release (Demo2)"
          PROVISIONING_PROFILE: "Censo Mobile Demo 2 AppStore"
        run: ./.github/scripts/archive_app.sh
      - name: Upload dSYMs to RayGun
        env:
          RAYGUN_ACCESS_TOKEN: ${{ secrets.RAYGUN_ACCESS_TOKEN }}
          RAYGUN_APPLICATION_ID: ${{ secrets.RAYGUN_APPLICATION_ID_DEMO }}
        run: ./.github/scripts/upload_dsyms.sh
      - name: Export .ipa
        env:
          EXPORT_OPTIONS_PLIST: "Censo/ExportOptions.plist"
        run: ./.github/scripts/export_ipa.sh
      - name: Publish app to TestFlight
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        if: success()
        run: ./.github/scripts/publish_testflight.sh
