name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Test iOS app
    runs-on: macos-11.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: SSH Agent
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.STRIKE_SSH_PRIVATE_KEY_GITHUB_ACTIONS }}
      - name: Add GitHub to known_hosts
        run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - name: Force Xcode 14.1
        run: sudo xcode-select -switch /Applications/Xcode_14.1.app
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
